import os

os.mkdir('project//results')
os.mkdir('project//testing')
os.mkdir('project//word_embeddings//glove.6B')
os.mkdir('project//wikidata//resources')
os.mkdir('project//wikidata//resources//wikidata_30-11-18')
os.mkdir('project//wikidata//resources//wikidata_ukp')
ok.mkdir('wikidata-access//results')
os.mkdir('wikidata-access//results//UKPSententialArgMin')
os.mkdir('wikidata-access//results//UKPSententialArgMin//knowledge_graph')
os.mkdir('wikidata-access//results//UKPSententialArgMin//knowledge_graph//wikidata_no_paths')

os.rename('project//data//abortion.tsv', 'project//testing//abortion.tsv')
os.rename('project//data//cloning.tsv', 'project//testing//cloning.tsv')
os.rename('project//data//death_penalty.tsv', 'project//testing//death_penalty.tsv')
os.rename('project//data//gun_control.tsv', 'project//testing//gun_control.tsv')
os.rename('project//data//marijuana_legalization.tsv', 'project//testing//marijuana_legalization.tsv')
os.rename('project//data//minimum_wage.tsv', 'project//testing//minimum_wage.tsv')
os.rename('project//data//nuclear_energy.tsv', 'project//testing//nuclear_energy.tsv')
os.rename('project//data//school_uniforms.tsv', 'project//testing//school_uniforms.tsv')
os.rename('project//data//glove.6B.100d.txt', 'project//word_embeddings//glove.6B//glove.6B.100d.txt')
os.rename('project//data//glove.6B.200d.txt', 'project//word_embeddings//glove.6B//glove.6B.200d.txt')
os.rename('project//data//glove.6B.300d.txt', 'project//word_embeddings//glove.6B//glove.6B.300d.txt')
os.rename('project//data//glove.6B.50d.txt', 'project//word_embeddings//glove.6B//glove.6B.50d.txt')
os.rename('project//data//property_frequencies.json', 'project//entity_properties//property_frequencies.json')
os.rename('project//data//properties_with_labels.txt', 'project//resources//properties_with_labels.txt')
os.rename('project//data//wikidata_30-11-18//property_frequencies.json', 'project//wikidata//resources//wikidata_30-11-18//property_frequencies.json')
os.rename('project//data//wikidata_30-11-18//property_frequencies_raw.txt', 'project//wikidata//resources//wikidata_30-11-18//property_frequencies_raw.txt')
os.rename('project//data//wikidata_ukp//properties_with_labels.txt', 'project//wikidata//resources//wikidata_ukp//properties_with_labels.txt')
os.rename('project//data//wikidata_ukp//property_blacklist.txt', 'project//wikidata//resources//wikidata_ukp//property_blacklist.txt')
print('done moving')