import os

os.mkdir('results')
os.mkdir('testing')
os.mkdir('word_embeddings//glove.6B')
os.mkdir('wikidata//resources')
os.mkdir('wikidata//resources//wikidata_30-11-18')
os.mkdir('wikidata//resources//wikidata_ukp')

os.rename('data//abortion.tsv', 'testing//abortion.tsv')
os.rename('data//cloning.tsv', 'testing//cloning.tsv')
os.rename('data//death_penalty.tsv', 'testing//death_penalty.tsv')
os.rename('data//gun_control.tsv', 'testing//gun_control.tsv')
os.rename('data//marijuana_legalization.tsv', 'testing//marijuana_legalization.tsv')
os.rename('data//minimum_wage.tsv', 'testing//minimum_wage.tsv')
os.rename('data//nuclear_energy.tsv', 'testing//nuclear_energy.tsv')
os.rename('data//school_uniforms.tsv', 'testing//school_uniforms.tsv')
os.rename('data//glove.6B.100d.txt', 'word_embeddings//glove.6B//glove.6B.100d.txt')
os.rename('data//glove.6B.200d.txt', 'word_embeddings//glove.6B//glove.6B.200d.txt')
os.rename('data//glove.6B.300d.txt', 'word_embeddings//glove.6B//glove.6B.300d.txt')
os.rename('data//glove.6B.50d.txt', 'word_embeddings//glove.6B//glove.6B.50d.txt')
os.rename('data//property_frequencies.json', 'entity_properties//property_frequencies.json')
os.rename('data//properties_with_labels.txt', 'resources//properties_with_labels.txt')
os.rename('data//wikidata_30-11-18//property_frequencies.json', 'wikidata//resources//wikidata_30-11-18//property_frequencies.json')
os.rename('data//wikidata_30-11-18//property_frequencies_raw.txt', 'wikidata//resources//wikidata_30-11-18//property_frequencies_raw.txt')
os.rename('data//wikidata_ukp//properties_with_labels.txt', 'wikidata//resources//wikidata_ukp//properties_with_labels.txt')
os.rename('data//wikidata_ukp//property_blacklist.txt', 'wikidata//resources//wikidata_ukp//property_blacklist.txt')
print('done moving')